DROP TABLE IF EXISTS complaints_raw;

CREATE TABLE complaints_raw (
    ObjectId TEXT,
    id TEXT,
    complaint_number TEXT,
    submit_date TEXT,
    submit_time TEXT,
    complaint_type TEXT,
    complaint_input TEXT,
    complaint_inspector TEXT,
    complaint_status TEXT,
    complaint_outcome TEXT,
    food_complaint TEXT,
    farm_animal TEXT,
    insect_vermin TEXT,
    odor_type TEXT,
    odor_strength TEXT,
    problem_location_name TEXT,
    problem_address TEXT,
    problem_street_direction TEXT,
    problem_street_name TEXT,
    problem_street_type TEXT,
    problem_unit_number TEXT,
    problem_city TEXT,
    problem_zip_code TEXT,
    problem_date_time TEXT,
    mac_complaint_id TEXT,
    permanent_parcel_number TEXT,
    census_tract TEXT,
    ward_number TEXT,
    submit_datetime TEXT,
    dw_ward TEXT,
    dw_ward_2014 TEXT,
    dw_ward_2026 TEXT,
    dw_neighborhood TEXT,
    dw_census_tract TEXT,
    dw_parcel TEXT
);
